spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true  # Add this line
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${ALLOWED_ORIGINS:http://localhost:5173}
            allowedMethods:
              - ${ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
            allowedHeaders:
              - ${ALLOWED_HEADERS:Authorization,Content-Type,Accept}
            allowCredentials: true
            maxAge: ${CORS_MAX_AGE:3600}
      routes:
        # Public routes first
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin

        - id: events-public
          uri: lb://event-service
          predicates:
            - Path=/api/events/public/**

        - id: clubs-public
          uri: lb://CLUBS
          predicates:
            - Path=/api/clubs/public/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin

        # Protected routes after

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
          filters:
            - AuthenticationFilter
            - DedupeResponseHeader=Access-Control-Allow-Origin

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:H8hS3jF5kL9qW7nE4zR6tU5yB2vM8pC1}
